name: resto
description: "950 Project"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.6
  form_field_validator: ^1.1.0
  http: ^1.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  u_credit_card: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/Illustrations/
    - assets/icons/
